<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;netstandard2.0;netstandard2.1;net48;net47;</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Deterministic + SourceLink -->
		<Deterministic>true</Deterministic>
		<DebugType>portable</DebugType>
		<EmbedAllSources>true</EmbedAllSources>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<EnableSourceLink>true</EnableSourceLink>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<IncludeSource>true</IncludeSource>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>

		<!-- Package Info -->
		<Title>Easy.Tools.Finance.CBAR</Title>
		<AssemblyTitle>Easy.Tools.Finance.CBAR</AssemblyTitle>
		<AssemblyName>Easy.Tools.Finance.CBAR</AssemblyName>
		<PackageId>Easy.Tools.Finance.CBAR</PackageId>
		<Version>1.0.4</Version>
		<PackageIcon>icon.png</PackageIcon>
		<Authors>Elmin Alirzayev</Authors>
		<Company>Easy Code Tools</Company>
		<Copyright>Copyright © Elmin Alirzayev 2025</Copyright>
		<Description>A lightweight .NET library for fetching exchange rates from the Central Bank of Azerbaijan (CBAR/AMB).</Description>
		<PackageTags>cbar amb azerbaijan manat azn finance currency exchange-rates xml azərbaycan mərkəzi bank məzənnə qızıl valyuta dollar avro kurs</PackageTags>	<RepositoryUrl>https://github.com/elminalirzayev/Easy.Tools.Finance.CBAR</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/elminalirzayev/Easy.Tools.Finance.CBAR</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes>Initial release: Supports daily rate fetching, retry logic, and DI integration.</PackageReleaseNotes>

		<!-- Build -->
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
		<LangVersion>latest</LangVersion>

	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>true</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="icon.png">
			<Pack>true</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net47' Or '$(TargetFramework)' == 'net472' Or '$(TargetFramework)' == 'net48'">
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
	</ItemGroup>

</Project>
